
export const templates = [
  {
    id: 'invoice',
    name: 'templateInvoice',
    mergeCells: [
      { row: 0, col: 0, rowspan: 1, colspan: 6 },
      { row: 15, col: 0, rowspan: 1, colspan: 6 },
    ],
    data: [
      [{ value: 'INVOICE', className: 'ht-cell-bold ht-bg-light-blue ht-text-black htCenter', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }],
      [],
      [{ value: 'Billed To:', className: 'ht-cell-bold' }, 'Client Name', '', { value: 'Invoice #:', className: 'ht-cell-bold htRight' }, '1001', ''],
      [{ value: 'Address:', className: 'ht-cell-bold' }, 'Client Address', '', { value: 'Date:', className: 'ht-cell-bold htRight' }, { value: new Date(), type: 'date', dateFormat: 'MM/DD/YYYY' }, ''],
      [{ value: 'Email:', className: 'ht-cell-bold' }, 'client@email.com', '', { value: 'Due Date:', className: 'ht-cell-bold htRight' }, { value: new Date(new Date().setDate(new Date().getDate() + 30)), type: 'date', dateFormat: 'MM/DD/YYYY' }, ''],
      [],
      [{ value: 'Item Description', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Notes', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Qty', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Unit Price', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Total', className: 'ht-cell-bold ht-bg-light-gray htRight' }, ''],
      ['Example Item 1', 'Detailed note 1', {value: 2, className: 'htCenter'}, { value: 150.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C8*D8', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
      ['Example Item 2', 'Detailed note 2', {value: 1, className: 'htCenter'}, { value: 450.50, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C9*D9', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
      ['Example Item 3', 'Detailed note 3', {value: 5, className: 'htCenter'}, { value: 50.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C10*D10', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
      [],
      ['', '', '', { value: 'Subtotal:', className: 'ht-cell-bold htRight' }, { value: '=SUM(E8:E10)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, ''],
      ['', '', '', { value: 'Tax (10%):', className: 'ht-cell-bold htRight' }, { value: '=E12*0.1', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, ''],
      ['', '', '', { value: 'Total:', className: 'ht-cell-bold htRight' }, { value: '=E12+E13', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }, ''],
      [],
      [{ value: 'Thank you for your business!', className: 'ht-cell-italic htCenter' }, '', '', '', '', ''],
    ],
  },
  {
    id: 'ganttChart',
    name: 'templateGantt',
    mergeCells: [
      { row: 0, col: 0, rowspan: 1, colspan: 7 },
      { row: 0, col: 7, rowspan: 1, colspan: 7 },
    ],
    data: [
      [{ value: 'Project Management: Gantt Chart', className: 'ht-cell-bold ht-bg-light-blue htCenter', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: 'Timeline', className: 'ht-cell-bold ht-bg-light-blue htCenter', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }, { value: null, className: 'ht-bg-light-blue', readOnly: true }],
      [],
      [{ value: 'Task', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Owner', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Start Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'End Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Duration', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Status', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Progress', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Wk 1', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 2', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 3', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 4', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 5', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 6', className: 'ht-cell-bold ht-bg-light-gray htCenter' }, { value: 'Wk 7', className: 'ht-cell-bold ht-bg-light-gray htCenter' }],
      ['Phase 1: Planning', 'A. Manager', { value: '2024-07-01', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '2024-07-05', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '=D4-C4', comment: { value: "Duration in days" } }, 'Completed', { value: 1, type: 'numeric', numericFormat: { pattern: '0%' } }, { className: 'ht-bg-light-green' }, '', '', '', '', '', ''],
      ['Phase 2: Design', 'C. Designer', { value: '2024-07-08', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '2024-07-19', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '=D5-C5' }, 'In Progress', { value: 0.5, type: 'numeric', numericFormat: { pattern: '0%' } }, '', { className: 'ht-bg-light-yellow' }, { className: 'ht-bg-light-yellow' }, '', '', '', ''],
      ['Phase 3: Development', 'D. Dev', { value: '2024-07-22', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '2024-08-16', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '=D6-C6' }, 'Not Started', { value: 0, type: 'numeric', numericFormat: { pattern: '0%' } }, '', '', '', { className: 'ht-bg-light-blue' }, { className: 'ht-bg-light-blue' }, { className: 'ht-bg-light-blue' }, { className: 'ht-bg-light-blue' }],
      ['Phase 4: Testing', 'F. Tester', { value: '2024-08-19', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '2024-08-23', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '=D7-C7' }, 'Blocked', { value: 0, type: 'numeric', numericFormat: { pattern: '0%' }, className: 'ht-text-dark-red' } , '', '', '', '', '', '', { className: 'ht-bg-light-red' }],
      ['Phase 5: Deployment', 'A. Manager', { value: '2024-08-26', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '2024-08-30', type: 'date', dateFormat: 'YYYY-MM-DD' }, { value: '=D8-C8' }, 'Not Started', { value: 0, type: 'numeric', numericFormat: { pattern: '0%' } }, '', '', '', '', '', '', ''],
    ]
  },
  {
    id: 'generalLedger',
    name: 'templateGeneralLedger',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 6 } ],
    data: [
        [{ value: 'General Ledger', className: 'ht-cell-bold ht-bg-light-blue htCenter' }, { value: null, className: 'ht-bg-light-blue' }, { value: null, className: 'ht-bg-light-blue' }, { value: null, className: 'ht-bg-light-blue' }, { value: null, className: 'ht-bg-light-blue' }, { value: null, className: 'ht-bg-light-blue' }],
        [{ value: 'Account:', className: 'ht-cell-bold' }, 'Cash', { value: 'Account #:', className: 'ht-cell-bold' }, '10100'],
        [],
        [{ value: 'Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Transaction ID', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Description', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Debit', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Credit', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Balance', className: 'ht-cell-bold ht-bg-light-gray htRight' }],
        [{ value: '2024-07-01', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'JV-001', 'Initial Balance', { value: null }, { value: null }, { value: 10000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-07-02', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'SALE-001', 'Sale of goods', { value: 5000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: null }, { value: '=F5+D6-E6', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-07-03', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'EXP-001', 'Office Supplies', { value: null }, { value: 250, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=F6+D7-E7', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-07-05', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'PAY-001', 'Payroll Expense', { value: null }, { value: 3000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=F7+D8-E8', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-07-10', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'SALE-002', 'Consulting Service', { value: 2500, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: null }, { value: '=F8+D9-E9', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [],
        [null, null, { value: 'Ending Balance', className: 'ht-cell-bold htRight' }, { value: '=SUM(D5:D9)', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=SUM(E5:E9)', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=F9', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }]
    ]
  },
  {
    id: 'salesLedger',
    name: 'templateSalesLedger',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 6 } ],
    data: [
      [{ value: 'Sales Ledger (Accounts Receivable)', className: 'ht-cell-bold ht-bg-light-blue htCenter' }, null, null, null, null, null],
      [{ value: 'Customer:', className: 'ht-cell-bold' }, 'Example Corp'],
      [],
      [{ value: 'Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Description', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Invoice #', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Debit (Invoice)', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Credit (Payment)', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Balance', className: 'ht-cell-bold ht-bg-light-gray htRight' }],
      [{value: '2024-07-01', type: 'date'}, 'Initial Balance', 'INV-000', null, null, {value: 0, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-05', type: 'date'}, 'Product Sale', 'INV-101', {value: 1200, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, null, {value: '=F5+D6-E6', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-15', type: 'date'}, 'Service Rendered', 'INV-102', {value: 850.50, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, null, {value: '=F6+D7-E7', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-20', type: 'date'}, 'Payment Received', 'PMT-050', null, {value: 1200, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=F7+D8-E8', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [],
      [null, null, { value: 'Total Due', className: 'ht-cell-bold htRight' }, {value: '=SUM(D5:D8)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=SUM(E5:E8)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=F8', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold'}]
    ]
  },
   {
    id: 'purchaseLedger',
    name: 'templatePurchaseLedger',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 6 } ],
    data: [
      [{ value: 'Purchase Ledger (Accounts Payable)', className: 'ht-cell-bold ht-bg-light-blue htCenter' }, null, null, null, null, null],
      [{ value: 'Supplier:', className: 'ht-cell-bold' }, 'Global Supplies Inc.'],
      [],
      [{ value: 'Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Description', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Invoice #', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Debit (Payment)', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Credit (Invoice)', className: 'ht-cell-bold ht-bg-light-gray htRight' }, { value: 'Balance Owed', className: 'ht-cell-bold ht-bg-light-gray htRight' }],
      [{value: '2024-07-01', type: 'date'}, 'Initial Balance', 'INV-000', null, null, {value: 0, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-03', type: 'date'}, 'Raw Materials', 'GS-5521', null, {value: 5000, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=F5-D6+E6', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-10', type: 'date'}, 'Office Equipment', 'GS-5598', null, {value: 1500, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=F6-D7+E7', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [{value: '2024-07-25', type: 'date'}, 'Payment Made', 'CHK-1023', {value: 5000, type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, null, {value: '=F7-D8+E8', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}],
      [],
      [null, null, { value: 'Total Owed', className: 'ht-cell-bold htRight' }, {value: '=SUM(D5:D8)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=SUM(E5:E8)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }}, {value: '=F8', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold'}]
    ]
  },
  {
    id: 'payroll',
    name: 'templatePayroll',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 7 } ],
    data: [
        [{ value: 'Payroll Summary', className: 'ht-cell-bold ht-bg-light-blue htCenter' }, '', '', '', '', '', ''],
        ['Pay Period:', 'MM/DD/YYYY - MM/DD/YYYY', '', '', '', '', ''],
        [],
        [{ value: 'Employee Name', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Pay Rate', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Hours Worked', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Gross Pay', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Taxes (20%)', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Net Pay', className: 'ht-cell-bold ht-bg-light-gray' }, ''],
        ['John Doe', { value: 25.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, 40, { value: '=B5*C5', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D5*0.2', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D5-E5', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
        ['Jane Smith', { value: 30.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, 38, { value: '=B6*C6', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D6*0.2', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D6-E6', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
        ['Peter Jones', { value: 22.50, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, 42, { value: '=B7*C7', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D7*0.2', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=D7-E7', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, ''],
        [],
        [{ value: 'Totals', className: 'ht-cell-bold' }, '', { value: '=SUM(C5:C7)' }, { value: '=SUM(D5:D7)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow ht-cell-bold' }, { value: '=SUM(E5:E7)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow ht-cell-bold' }, { value: '=SUM(F5:F7)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }, ''],
    ],
  },
  {
    id: 'expenseReimbursement',
    name: 'templateExpense',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 4 } ],
    data: [
        [{ value: 'Expense Reimbursement Form', className: 'ht-cell-bold ht-bg-light-blue htCenter' }, '', '', ''],
        [{ value: 'Employee Name:', className: 'ht-cell-bold' }, 'Your Name', { value: 'Department:', className: 'ht-cell-bold' }, 'Your Department'],
        [{ value: 'Report Period:', className: 'ht-cell-bold' }, ''],
        [],
        [{ value: 'Date', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Category', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Description', className: 'ht-cell-bold ht-bg-light-gray' }, { value: 'Amount', className: 'ht-cell-bold ht-bg-light-gray' }],
        [{ value: '2024-01-05', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'Travel', 'Client Meeting Lunch', { value: 55.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-01-06', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'Office Supplies', 'New Keyboard', { value: 75.99, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{ value: '2024-01-08', type: 'date', dateFormat: 'YYYY-MM-DD' }, 'Travel', 'Taxi to airport', { value: 40.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [],
        ['', '', { value: 'Total:', className: 'ht-cell-bold htRight' }, { value: '=SUM(D6:D8)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
    ],
  },
  {
    id: 'balanceSheet',
    name: 'templateBalanceSheet',
    data: [
        [{value: 'Balance Sheet', className: 'ht-cell-bold ht-bg-light-blue'}, {value: null, className: 'ht-bg-light-blue'}, {value: 'As of Date:', className: 'ht-cell-bold htRight ht-bg-light-blue'}, {value: new Date(), type: 'date', dateFormat: 'MM/DD/YYYY', className: 'ht-bg-light-blue'}],
        [],
        [{ value: 'ASSETS', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['Current Assets'],
        ['', 'Cash and Cash Equivalents', { value: 150000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', 'Accounts Receivable', { value: 75000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', 'Inventory', { value: 50000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', {value: 'Total Current Assets', className: 'ht-cell-bold'}, { value: '=SUM(C5:C7)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        ['Non-Current Assets'],
        ['', 'Property, Plant, and Equipment', { value: 350000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', 'Intangible Assets', { value: 25000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', {value: 'Total Non-Current Assets', className: 'ht-cell-bold'}, { value: '=SUM(C11:C12)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'TOTAL ASSETS', className: 'ht-cell-bold'}, '', { value: '=C8+C13', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
        [],
        [{ value: 'LIABILITIES AND EQUITY', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['Current Liabilities'],
        ['', 'Accounts Payable', { value: 60000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', 'Short-term Debt', { value: 40000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', {value: 'Total Current Liabilities', className: 'ht-cell-bold'}, { value: '=SUM(C19:C20)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        ['Non-Current Liabilities'],
        ['', 'Long-term Debt', { value: 200000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', {value: 'Total Non-Current Liabilities', className: 'ht-cell-bold'}, { value: '=C24', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'Total Liabilities', className: 'ht-cell-bold'}, '', { value: '=C21+C25', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
        [],
        ['Shareholders\' Equity'],
        ['', 'Common Stock', { value: 100000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', 'Retained Earnings', { value: 250000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['', {value: 'Total Equity', className: 'ht-cell-bold'}, { value: '=SUM(C30:C31)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'TOTAL LIABILITIES AND EQUITY', className: 'ht-cell-bold'}, '', { value: '=C27+C32', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
    ],
  },
  {
    id: 'incomeStatement',
    name: 'templateIncomeStatement',
    data: [
        [{value: 'Income Statement (P&L)', className: 'ht-cell-bold ht-bg-light-blue'}, {value: null, className: 'ht-bg-light-blue'}],
        [{value: 'For the period ending:', className: 'ht-cell-bold'}, new Date().toISOString().split('T')[0]],
        [],
        ['Revenue', { value: 1000000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['Cost of Goods Sold (COGS)', { value: -450000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Gross Profit', className: 'ht-cell-bold'}, { value: '=SUM(B4:B5)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{ value: 'Operating Expenses', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['  Sales, General & Admin', { value: -250000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Research & Development', { value: -100000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Total Operating Expenses', className: 'ht-cell-bold'}, { value: '=SUM(B9:B10)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'Operating Income (EBIT)', className: 'ht-cell-bold'}, { value: '=B6+B11', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        ['Interest Expense', { value: -20000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Income Before Tax', className: 'ht-cell-bold'}, { value: '=B13+B14', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['Income Tax Expense (30%)', { value: '=B15*-0.3', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Net Income', className: 'ht-cell-bold'}, { value: '=B15+B16', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
    ],
  },
  {
    id: 'cashFlow',
    name: 'templateCashFlow',
    data: [
        [{ value: 'Cash Flow Statement', className: 'ht-cell-bold ht-bg-light-blue' }, {value: null, className: 'ht-bg-light-blue'}],
        [{value: 'For the period ending:', className: 'ht-cell-bold'}, new Date().toISOString().split('T')[0]],
        [],
        [{ value: 'Cash Flow from Operating Activities', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['  Net Income', { value: 250000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Depreciation & Amortization', { value: 50000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Changes in Working Capital', { value: -20000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Net Cash from Operating Activities', className: 'ht-cell-bold'}, { value: '=SUM(B5:B7)', className: 'ht-bg-light-yellow', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [],
        [{ value: 'Cash Flow from Investing Activities', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['  Purchase of Equipment', { value: -150000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Sale of Assets', { value: 25000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Net Cash from Investing Activities', className: 'ht-cell-bold'}, { value: '=SUM(B11:B12)', className: 'ht-bg-light-yellow', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [],
        [{ value: 'Cash Flow from Financing Activities', className: 'ht-cell-bold ht-bg-light-gray' }],
        ['  Issuance of Stock', { value: 10000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Repayment of Debt', { value: -50000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Net Cash from Financing Activities', className: 'ht-cell-bold'}, { value: '=SUM(B16:B17)', className: 'ht-bg-light-yellow', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [],
        [{value: 'Net Change in Cash', className: 'ht-cell-bold'}, { value: '=B8+B13+B18', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Beginning Cash Balance', className: 'ht-cell-bold'}, { value: 100000, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Ending Cash Balance', className: 'ht-cell-bold'}, { value: '=B20+B21', className: 'ht-bg-light-green ht-cell-bold', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
    ],
  },
  {
    id: 'budget',
    name: 'templateBudget',
    mergeCells: [ { row: 0, col: 0, rowspan: 1, colspan: 4 } ],
    data: [
        [{ value: 'Monthly Budget', className: 'ht-cell-bold ht-bg-light-blue htCenter'}, null, null, null],
        [],
        [{value: 'Income', className: 'ht-cell-bold ht-bg-light-gray'}, {value: 'Budgeted', className: 'ht-cell-bold ht-bg-light-gray htRight'}, {value: 'Actual', className: 'ht-cell-bold ht-bg-light-gray htRight'}, {value: 'Difference', className: 'ht-cell-bold ht-bg-light-gray htRight'}],
        ['  Salary', { value: 5000.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 5000.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C4-B4', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Other', { value: 200.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 150.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C5-B5', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Total Income', className: 'ht-cell-bold'}, { value: '=SUM(B4:B5)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, { value: '=SUM(C4:C5)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, { value: '=C6-B6', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'Expenses', className: 'ht-cell-bold ht-bg-light-gray'}, {value: 'Budgeted', className: 'ht-cell-bold ht-bg-light-gray htRight'}, {value: 'Actual', className: 'ht-cell-bold ht-bg-light-gray htRight'}, {value: 'Difference', className: 'ht-cell-bold ht-bg-light-gray htRight'}],
        ['  Rent/Mortgage', { value: 1500.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 1500.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C9-B9', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Utilities', { value: 200.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 225.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C10-B10', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Groceries', { value: 600.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 550.75, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C11-B11', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Transportation', { value: 150.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 180.25, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C12-B12', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        ['  Entertainment', { value: 250.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: 300.00, type: 'numeric', numericFormat: { pattern: '$0,0.00' } }, { value: '=C13-B13', type: 'numeric', numericFormat: { pattern: '$0,0.00' } }],
        [{value: 'Total Expenses', className: 'ht-cell-bold'}, { value: '=SUM(B9:B13)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, { value: '=SUM(C9:C13)', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }, { value: '=C14-B14', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-yellow' }],
        [],
        [{value: 'Net Savings', className: 'ht-cell-bold'}, { value: '=B6-B14', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }, { value: '=C6-C14', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }, { value: '=C16-B16', type: 'numeric', numericFormat: { pattern: '$0,0.00' }, className: 'ht-bg-light-green ht-cell-bold' }],
    ],
  }
];
