
'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  dir: 'ltr' | 'rtl';
}

const translations: { [key in Language]: { [key: string]: string } } = {
  en: {
    pageTitle: 'Abdullah Banking',
    initialMessage: "Hello! I'm Abdullah, your financial advisor. How can I help you today?",
    placeholder: "Message Abdullah...",
    uploadCsvTooltip: "Upload Loan CSV",
    uploadPdfTooltip: "Upload Financial PDF",
    micTooltip: "Use Microphone",
    sendSr: "Send",
    analyzingFile: "Context: {{fileName}}",
    clearPdfTooltip: "Clear PDF from session",
    pdfClearedTitle: "PDF Cleared",
    pdfClearedDesc: "The document has been removed from the session.",
    clearedPdfMessage: "I have cleared the previous document. How can I assist you now?",
    csvUploadTitle: "CSV File Uploaded",
    csvUploadDesc: "{{fileName}} is ready for loan analysis.",
    pdfUploadTitle: "PDF File Uploaded",
    pdfUploadDesc: "{{fileName}} is ready for analysis.",
    pdfLoadedForChat: "I've loaded {{fileName}}. Feel free to ask me any questions about it.",
    analyzingPdfMessage: "Analyzing financial statement: {{fileName}}...",
    analysisFailedTitle: "Analysis Failed",
    analysisFailedDesc: "Abdullah could not analyze the document. Please ensure it's a valid financial statement and try again.",
    unableToAnalyzeMessage: 'Sorry, I was unable to analyze that document.',
    loanAnalysisHeader: "Here is the analysis for Loan ID **{{loanId}}**:",
    financialAnalysisHeader: "Here is the analysis of the financial statement:",
    uploadCsvFirst: 'Please upload a CSV file before requesting a loan analysis.',
    invalidPdfTitle: 'Invalid File Type',
    invalidPdfDesc: 'Please upload a PDF file.',
    sessionSaveErrorTitle: 'Could not save session',
    sessionSaveErrorDesc: 'Your browser may be out of space or in private mode.',
    documentLoadedTitle: 'Document Loaded',
    documentLoadedDesc: "Continuing session with {{fileName}}.",
    genericErrorTitle: 'Oh no! Something went wrong.',
    genericErrorDesc: 'Failed to get a response from Abdullah. Please try again.',
    loanAnalysisReportTitle: "Loan Analysis Report",
    financialAnalysisReportTitle: "Financial Statement Analysis",
    summary: "Summary",
    prediction: "Prediction",
    eligibility: "Eligibility",
    creditScoreAssessment: "Credit Score Assessment",
    downloadPdf: "Download PDF",
    english: 'English',
    arabic: 'Arabic',
    choosePdfLanguageTitle: "Choose PDF Language",
    choosePdfLanguageDesc: "In which language would you like to download the report?",
    cancel: "Cancel",
    clearCsvTooltip: "Clear CSV from session",
    csvClearedTitle: "CSV Cleared",
    csvClearedDesc: "The CSV data has been cleared from the session.",
    clearedCsvMessage: "I have cleared the CSV data. How can I help you now?",
    translationErrorTitle: 'Translation Error',
    translationErrorDesc: 'Failed to generate the report in {{lang}}. Please try again.',
    generatingTranslatedPdf: 'Generating translated PDF...',
    trendsAndGraphsTitle: "Trends & Visualizations",
    identifiedFlawsTitle: "Identified Flaws & Risks",
    financialPerformanceTitle: "Financial Performance",
    revenue: "Revenue",
    netIncome: "Net Income",
    pdfGenerationError: "Could not generate the PDF report.",
    maintenanceMessage: "Services are undergoing maintenance and major upgrades. Time remaining: {{time}}",
    
    // Abdullah Vision
    abdullahVisionTitle: "Abdullah Vision",
    abdullahVisionDesc: "A creative space to generate and enhance images using AI.",
    textToImageTitle: "Text-to-Image",
    textToImageDesc: "Describe the image you want to create.",
    imageEnhancementTitle: "Image Enhancement",
    imageEnhancementDesc: "Upload an image to upscale its quality.",
    videoEnhancementTitle: "Video Enhancement (Soon)",
    videoEnhancementDesc: "Upload a video to improve its resolution and clarity.",
    promptLabel: "Prompt",
    promptPlaceholder: "e.g., A photorealistic image of a cat wearing a small hat, sitting in a library",
    generateButton: "Generate",
    generatingMessage: "Abdullah is creating your image...",
    uploadButton: "Upload Image",
    upscaleButton: "Upscale Image",
    upscalingMessage: "Abdullah is enhancing your image...",
    uploadVideo: "Upload Video",
    resultTitle: "Result",
    noResult: "Your generated or enhanced image will appear here.",
    imageGenFailedTitle: "Image Generation Failed",
    imageGenFailedDesc: "Sorry, I couldn't create an image at this time. Please try again later.",
    imageUpscaleFailedTitle: "Image Upscaling Failed",
    imageUpscaleFailedDesc: "Sorry, I couldn't enhance the image. Please ensure it's a valid format and try again.",
    downloadButton: "Download",
    startOver: "Start Over",

    newSessionButton: "New Session",
    newSessionTitle: "New Session Started",
    newSessionDesc: "Your chat has been cleared.",
    newSessionDescSpreadsheet: "Your spreadsheet and chat have been cleared.",
    newSessionDescDA: "Your data analysis dashboard has been cleared.",
    newSessionConfirmTitle: "Are you sure?",
    newSessionConfirmDescChat: "This will clear your entire chat history and remove any uploaded files. This action cannot be undone.",
    newSessionConfirmDescSpreadsheet: "This will clear your entire spreadsheet, including data and charts, and reset the chat. This action cannot be undone.",
    newSessionConfirmButton: "Start New Session",

    // Abdullah Status
    abdullahStatusOnline: 'Online',
    abdullahStatusOffline: 'Offline',
    
    // Nav
    chatTitle: 'Chat',
    aboutTitle: 'About Abdullah',
    spreadsheetTitle: 'Spreadsheet',
    spreadsheetGuideTitle: 'Spreadsheet Guide',
    dataAnalyticsTitle: 'Data Analytics',
    knowledgeBaseTitle: 'Knowledge Base',

    // Knowledge Base Page
    kbHeader: "Abdullah's Knowledge Base",
    kbSubHeader: "Add your own custom instructions, rules, or data that Abdullah will remember across all conversations. This is your personal extension to Abdullah's brain.",
    kbPlaceholder: "Enter your custom notes here...\n\nFor example:\n- Never suggest investing in cryptocurrency.\n- When I ask for a market summary, always include the VIX index.\n- My company's fiscal year ends in June.",
    kbSaveButton: 'Save Knowledge',
    kbSavingButton: 'Saving...',
    kbSaveSuccessTitle: 'Knowledge Base Saved',
    kbSaveSuccessDesc: "Abdullah's knowledge has been updated.",
    kbSaveErrorTitle: 'Save Failed',
    kbSaveErrorDesc: 'Could not save your notes. Please try again.',
    kbLoadErrorTitle: 'Load Failed',
    kbLoadErrorDesc: 'Could not load your knowledge base notes.',


    // Learn Page -> About Page
    learnPageTitle: 'About Abdullah',
    learnIntro: 'Abdullah is an advanced, AI-powered financial strategist and banking assistant designed to bring institutional-grade analysis and agentic task execution to your fingertips. Interact naturally, get deep insights, and automate complex tasks with ease.',
    learnCapabilitiesTitle: "Abdullah's Core Capabilities",
    capabilityHours: "Availability:",
    chatAvailability: "24/7",
    spreadsheetAvailability: "24/7",
    daAvailability: "24/7",
    learnChatTitle: 'Institutional-Grade Financial Intelligence',
    learnChatDesc: "Engage with an AI that understands the nuances of finance. Upload complex financial statements, credit reports from bureaus like Oman's Mala'a, or internal loan data. Abdullah doesn't just read; he comprehends, synthesizes, and critiques. Ask him to 'Identify key risks in this balance sheet,' 'Benchmark this company's P/E ratio against industry standards,' or 'Draft a summary for the credit committee.' Abdullah provides instant, institutional-quality analysis in both English and Arabic, becoming an indispensable partner for credit officers, analysts, and decision-makers.",
    learnAbdullahVisionDesc: "Unleash your creativity in a dedicated space. As a world-class creative director, Abdullah can generate photorealistic images from text descriptions or upscale your existing images to stunning high-resolution quality. Abdullah Vision is your partner for creating compelling visual assets.",
    learnSpreadsheetTitle: 'The Truly Agentic Spreadsheet',
    learnSpreadsheetDesc: "This is not just a spreadsheet; it's an intelligent workspace where you command an expert AI financial analyst with natural language. Say 'Create a 5-year DCF model for a SaaS company,' 'Generate a Gantt chart for the Q4 product launch,' or 'Analyze these sales figures and highlight all regions that underperformed by 15%.' Abdullah functions as a state-of-the-art AI agent, understanding your intent, structuring the data, applying complex formulas, and executing multi-step operations instantly. With a rich library of professional templates and a full suite of formatting tools, it transforms your productivity, rivaling traditional desktop applications.",
    learnDATitle: 'Conversational BI Dashboard',
    learnDADesc: "Transform raw data into actionable insights with a fully conversational BI engine. Upload CSV, Excel, or PDF files, and Abdullah will instantly generate an interactive dashboard with key metrics, charts, and tables. Continue the conversation to request new visualizations on the fly. Ask Abdullah to 'Show me total sales by region as a bar chart,' or 'create a pie chart for customer segments.' Abdullah acts as your personal data engineer and BI developer, turning complex data into clear, interactive visuals.",
    learnAITitle: 'Powered by a State-of-the-Art AI Architecture',
    learnAIDesc: "Abdullah is built on a private, state-of-the-art AI architecture. This enables him to understand complex documents, reason about data, follow multi-step instructions, and generate human-like text, making him a powerful and versatile financial partner.",
    learnSecurityTitle: 'Enterprise-Grade Security & Privacy',
    learnSecurityDesc: "Abdullah is engineered with security as a foundational principle. Operating within a private, state-of-the-art architecture, all data processing and interactions are handled with the strictest confidentiality. Your financial statements, proprietary data, and sensitive conversations are never used for external training models. With end-to-end encryption and robust access controls, Abdullah provides a secure, compliant environment that meets the rigorous standards of financial institutions, ensuring your most critical information remains protected.",
    learnWhoBenefitsTitle: 'Who Benefits from Abdullah?',
    learnRoleAnalystTitle: 'The Financial Analyst',
    learnRoleAnalystDesc: 'Accelerate your research, data modeling, and report generation. Let Abdullah handle the repetitive tasks so you can focus on strategic insights.',
    learnRoleOfficerTitle: 'The Credit Officer',
    learnRoleOfficerDesc: 'Gain a deeper, faster understanding of applicant risk. Analyze financial statements and credit reports in seconds to make more informed decisions.',
    learnRoleExecutiveTitle: 'The Executive',
    learnRoleExecutiveDesc: 'Access high-level summaries and key metrics on demand. Stay informed and drive strategy without getting bogged down in the details.',
    gettingStartedTitle: "Getting Started: A Quick Guide",
    gsChatStepTitle: "1. Start a Conversation",
    gsChatStepDesc: "Navigate to the <strong>Chat</strong> page. You can start talking to Abdullah immediately. For more powerful analysis, use the upload buttons in the message bar to provide a PDF or CSV file as context for your conversation.",
    gsSpreadsheetStepTitle: "2. Command Your Spreadsheet",
    gsSpreadsheetDesc: "Go to the <strong>Spreadsheet</strong> page. Use the integrated chat sidebar to give Abdullah commands. You can also import your own Excel files using the toolbar to have Abdullah work with your own data.",
    gsDAStepTitle: "3. Analyze Your Data",
    gsDAStepDesc: "Head to the <strong>Data Analytics</strong> page. Upload your dataset (Excel, CSV, PDF), and Abdullah will instantly build a dashboard. Use the chat to ask for more specific insights and visualizations.",
    
    comingSoonAbdullahTitle: "The Future of Abdullah: AI Capabilities",
    comingSoonAbdullahDesc: "Abdullah's evolution is relentless. Our roadmap is focused on building the most powerful, proactive AI financial agent.",
    csAbdullahFeature1: "Proactive Insights & Anomaly Detection",
    csAbdullahFeature2: "Real-time Market Data Integration (stocks, forex)",
    csAbdullahFeature3: "Personalized Financial Health Dashboards",
    csAbdullahFeature4: "Advanced Voice & Speech Interaction",
    csAbdullahFeature5: "Secure Document Vault & Management",
    csAbdullahFeature6: "Automated Report Generation & Scheduling",
    csAbdullahFeature7: "Predictive Cash Flow Forecasting",
    csAbdullahFeature8: "Calendar & Email Integration for Financial Reminders",
    csAbdullahFeature9: "Multi-document Cross-Referencing & Analysis",
    csAbdullahFeature10: "Goal-based Savings & Investment Planning",
    csAbdullahFeature11: "Secure API for Enterprise Integration",
    csAbdullahFeature12: "Natural Language Querying of Databases",
    csAbdullahFeature13: "Compliance & Regulatory Change Monitoring",
    csAbdullahFeature14: "Customer Sentiment Analysis from Communications",
    csAbdullahFeature15: "Custom Agentic Workflow Automation",

    comingSoonSpreadsheetTitle: "The Future of Spreadsheets: Agentic Power",
    comingSoonSpreadsheetDesc: "The spreadsheet is becoming a fully autonomous workspace, powered by Abdullah.",
    csSpreadsheetFeature1: "Natural Language Formula Generation",
    csSpreadsheetFeature2: "Automatic Chart & Graph Creation from Data",
    csSpreadsheetFeature3: "AI-Powered Data Validation Rules",
    csSpreadsheetFeature4: "Instant Pivot Table Creation via Chat",
    csSpreadsheetFeature5: "Automated Data Cleaning & Deduplication",
    csSpreadsheetFeature6: "Intelligent Conditional Formatting",
    csSpreadsheetFeature7: "Real-time Stock & Financial Data in Cells",
    csSpreadsheetFeature8: "Automated Data Import from Web Sources",
    csSpreadsheetFeature9: "Live Collaborative Editing with AI Assistance",
    csSpreadsheetFeature10: "Full Version History with AI Summaries",
    csSpreadsheetFeature11: "Advanced Scenario Analysis & Goal Seek",
    csSpreadsheetFeature12: "Automated report generation from templates",
    csSpreadsheetFeature13: "Integration with external data sources (APIs)",
    csSpreadsheetFeature14: "Python scripting within cells for advanced analysis",
    csSpreadsheetFeature15: "AI-powered data auditing and error tracing",

    
    comingSoonDATitle: "The Future of Analytics: An Agentic BI Engine",
    comingSoonDADesc: "We are evolving Abdullah into a fully-fledged, AI-native Business Intelligence platform that rivals traditional tools.",
    csDAFeature1: "Interactive Dashboard Generation from Chat",
    csDAFeature2: "Power Query-like Visual Data Transformation Tools",
    csDAFeature3: "Natural Language to DAX-style Expressions",
    csDAFeature4: "Automated Data Storytelling and Report Building",
    csDAFeature5: "Real-time Anomaly Detection and Alerts",
    csDAFeature6: "Predictive Analytics and Forecasting Models",
    csDAFeature7: "Multi-Source Data Joins and Blending",
    csDAFeature8: "AI-powered Root Cause Analysis",
    csDAFeature9: "Custom Visuals and API Extensibility",
    csDAFeature10: "Automated ETL Pipeline Creation",

    getStartedAbdullah: 'GET STARTED WITH ABDULLAH',
    getStartedSpreadsheet: 'Or, get started with the Spreadsheet',

    // Spreadsheet Page
    chatWithAbdullah: "Chat with Abdullah",
    closeChat: "Close chat",
    abdullahSpreadsheetHello: "Hello! I am a fully-featured agentic spreadsheet assistant. I can help you with data entry, financial modeling, charts, and more. How can I help you?",
    spreadsheetPlaceholder: "e.g., Create an invoice template",
    send: "Send",
    showChat: "Show Chat",
    hideChat: "Hide Chat",
    importSuccessTitle: "Import Successful",
    importSuccessDesc: "Successfully imported \"{{fileName}}\".",
    importFailedTitle: "Import Failed",
    importFailedDesc: "There was an error processing your Excel file.",
    abdullahSpreadsheetFileLoaded: "I've loaded \"{{fileName}}\" into the spreadsheet. How can I help you with it?",
    abdullahSpreadsheetError: "Sorry, I ran into an issue. Please try that again.",
    toolbarFile: "File",
    toolbarTemplates: "Templates",
    templateInvoice: "Invoice",
    templatePayroll: "Payroll",
    templateExpense: "Expense Reimbursement",
    templateBalanceSheet: "Balance Sheet",
    templateIncomeStatement: "Income Statement",
    templateCashFlow: "Cash Flow Statement",
    templateBudget: "Monthly Budget",
    templateGantt: "Project Gantt Chart",
    templateGeneralLedger: "General Ledger",
    templateSalesLedger: "Sales Ledger",
    templatePurchaseLedger: "Purchase Ledger",
    templateFinancialModel: '3-Statement Financial Model',
    templateDCF: 'DCF Valuation',
    templateAppliedTitle: "Template Applied",
    templateAppliedDesc: "The template has been loaded into the sheet.",
    toolbarHome: "Home",
    toolbarInsert: "Insert (Soon)",
    toolbarFormulas: "Formulas (Soon)",
    toolbarData: "Data (Soon)",
    toolbarReview: "Review (Soon)",
    toolbarView: "View (Soon)",
    toolbarFullscreen: "Fullscreen",
    toolbarExitFullscreen: "Exit Fullscreen",
    toolbarDownload: "Download",
    toolbarImport: "Import",
    tooltipPaste: "Paste (Ctrl/Cmd+V)",
    tooltipCut: "Cut",
    tooltipCopy: "Copy",
    tooltipFormatPainter: "Format Painter (Soon)",
    tooltipBold: "Bold",
    tooltipItalic: "Italic",
    tooltipUnderline: "Underline",
    tooltipFontColor: "Font Color",
    tooltipFillColor: "Fill Color",
    tooltipAlignLeft: "Align Left",
    tooltipCenter: "Center",
    tooltipAlignRight: "Align Right",
    tooltipWrapText: "Wrap Text",
    tooltipMergeCenter: "Merge & Center",
    tooltipAutoSum: "AutoSum (Soon)",
    tooltipSortFilter: "Sort & Filter (Soon)",
    tooltipFindSelect: "Find & Select (Soon)",
    chartsTitle: "Charts",
    
    // Spreadsheet Guide Page
    sgTitle: "Spreadsheet Guide",
    sgHeader: "The Agentic Spreadsheet",
    sgSubHeader: "This isn't just a grid of cells. It's an intelligent workspace where you command the AI to perform complex tasks. This guide will show you how.",
    sgCoreCapabilitiesTitle: "Core Capabilities",
    sgFeatureAIAssistantTitle: "AI Assistant",
    sgFeatureAIAssistantDesc: "Use natural language in the chat panel to command Abdullah to perform any task, from data entry to complex financial modeling.",
    sgFeatureTemplatesTitle: "Powerful Templates",
    sgFeatureTemplatesDesc: "Jumpstart your work with a library of professional, pre-built templates for accounting, finance, and project management.",
    sgFeatureFormulasTitle: "Full-Featured Formulas",
    sgFeatureFormulasDesc: "Leverage a massive library of hundreds of functions, just like in a traditional spreadsheet application. Abdullah can build formulas for you.",
    sgFeatureDataToolsTitle: "Advanced Data Tools",
    sgFeatureDataToolsDesc: "Ask Abdullah to sort, filter, find duplicates, or even create pivot-table-like summaries on the fly.",
    sgGettingStartedTitle: "How It Works: Your 3-Step Workflow",
    sgGettingStartedDesc: "Working with the Agentic Spreadsheet is a simple, conversational process.",
    sgStep1Title: "Start with Data",
    sgStep1Desc: "You can start with a blank sheet, import an existing Excel/CSV file, or select a pre-built template from the 'Templates' menu.",
    sgStep2Title: "Give Abdullah a Command",
    sgStep2Desc: "Use the chat panel on the right to tell Abdullah what you want to do in plain English or Arabic.",
    sgStep2Example: "Calculate the net profit for Q3 and highlight it in green.",
    sgStep3Title: "Review the Result",
    sgStep3Desc: "Abdullah will interpret your command, perform the necessary operations (like inserting formulas and applying formatting), and confirm the action. The sheet updates instantly.",
    sgStep3Example: "Done. I've calculated the net profit in cell E14 and applied the formatting.",
    sgAbdullahCommandsTitle: "Example Commands for Abdullah",
    sgCmdDataEntryTitle: "Data Entry & Bookkeeping",
    sgCmdDataEntryDesc: "Abdullah can act as your automated bookkeeper.",
    sgCmdDataEntryExample: "Record a sale of 500 units at $12.50 each to 'Example Corp' on today's date.",
    sgCmdFinancialAnalysisTitle: "Financial Analysis & Modeling",
    sgCmdFinancialAnalysisDesc: "Ask Abdullah to perform complex financial calculations.",
    sgCmdFinancialAnalysisExample: "What is the Net Present Value of cash flows in C5:C10 with a discount rate of 8%?",
    sgCmdFormattingTitle: "Formatting & Auditing",
    sgCmdFormattingDesc: "Automate visual organization and data validation.",
    sgCmdFormattingExample: "Find all rows where column D is greater than column C and make their background light red.",
    sgCmdChartsTitle: "Charts & Visualization",
    sgCmdChartsDesc: "Turn your data into insights.",
    sgCmdChartsExample: "Create a bar chart showing the total sales by region from columns A and F.",
    sgFunctionLibraryTitle: "Function & Formula Library",
    sgFunctionLibraryDesc: "Abdullah is proficient with a vast library of functions and can generate formulas on command. Here are some of the key functions available:",
    sgFuncMathLogicTitle: "Math & Logic",
    sgFuncLookupTitle: "Lookup & Reference",
    sgFuncFinancialTitle: "Financial",
    sgFuncTextTitle: "Text",
    sgFuncDateTimeTitle: "Date & Time",
    sgFuncStatisticalTitle: "Statistical & Forecasting",

    // Data Analytics Page
    daUploadPromptTitle: "AI-Powered Data Dashboard",
    daUploadPromptDesc: "Upload your data file (XLSX, CSV, or PDF) to have Abdullah analyze it and generate an interactive dashboard.",
    daUploadButton: "Upload Data File",
    daGeneratingDashboardTitle: "Generating AI Dashboard...",
    daGeneratingDashboardDesc: "Please wait while Abdullah analyzes your data and builds your dashboard.",
    analysisResultTitle: "Analysis Result",
    daSummaryTitle: "AI Summary",
    daUnsupportedFileType: 'Unsupported file type. Please upload a CSV, XLSX, or PDF file.',
    daAnalysisFailedDesc: 'Analysis failed. The file may be corrupt, in an unsupported format, or the AI model is currently unavailable.',
    daKeyInsightsTitle: 'Key Insights',
    daDownloadPdfButton: 'Download PDF',
    daGeneratingPdfTitle: 'Generating PDF Report...',
    daPdfGenerationFailedTitle: 'PDF Generation Failed',
    daPdfGenerationFailedDesc: 'An error occurred while trying to generate the PDF report.',
  },
  ar: {
    pageTitle: 'عبدالله المصرفية',
    initialMessage: "مرحباً! أنا عبدالله، مستشارك المالي. كيف يمكنني مساعدتك اليوم؟",
    placeholder: "راسل عبدالله...",
    uploadCsvTooltip: "تحميل ملف CSV للقروض",
    uploadPdfTooltip: "تحميل ملف PDF مالي",
    micTooltip: "استخدام الميكروفون",
    sendSr: "إرسال",
    analyzingFile: "السياق: {{fileName}}",
    clearPdfTooltip: "مسح ملف PDF من الجلسة",
    pdfClearedTitle: "تم مسح PDF",
    pdfClearedDesc: "تمت إزالة المستند من الجلسة.",
    clearedPdfMessage: "لقد قمت بمسح المستند السابق. كيف يمكنني مساعدتك الآن؟",
    csvUploadTitle: "تم تحميل ملف CSV",
    csvUploadDesc: "{{fileName}} جاهز لتحليل القرض.",
    pdfUploadTitle: "تم تحميل ملف PDF",
    pdfUploadDesc: "{{fileName}} جاهز للتحليل.",
    pdfLoadedForChat: "لقد قمت بتحميل {{fileName}}. لا تتردد في طرح أي أسئلة حوله.",
    analyzingPdfMessage: "جاري تحليل البيان المالي: {{fileName}}...",
    analysisFailedTitle: "فشل التحليل",
    analysisFailedDesc: "لم يتمكن عبدالله من تحليل المستند. يرجى التأكد من أنه بيان مالي صالح والمحاولة مرة أخرى.",
    unableToAnalyzeMessage: 'عذراً، لم أتمكن من تحليل ذلك المستند.',
    loanAnalysisHeader: "إليك تحليل معرف القرض **{{loanId}}**:",
    financialAnalysisHeader: "إليك تحليل البيان المالي:",
    uploadCsvFirst: 'يرجى تحميل ملف CSV قبل طلب تحليل القرض.',
    invalidPdfTitle: 'نوع ملف غير صالح',
    invalidPdfDesc: 'يرجى تحميل ملف PDF.',
    sessionSaveErrorTitle: 'تعذر حفظ الجلسة',
    sessionSaveErrorDesc: 'قد تكون مساحة متصفحك ممتلئة أو في وضع التصفح الخاص.',
    documentLoadedTitle: 'تم تحميل المستند',
    documentLoadedDesc: "متابعة الجلسة مع {{fileName}}.",
    genericErrorTitle: 'عفوًا! حدث خطأ ما.',
    genericErrorDesc: 'فشل الحصول على رد من عبدالله. يرجى المحاولة مرة أخرى.',
    loanAnalysisReportTitle: "تقرير تحليل القرض",
    financialAnalysisReportTitle: "تحليل البيان المالي",
    summary: "ملخص",
    prediction: "توقع",
    eligibility: "الأهلية",
    creditScoreAssessment: "تقييم الجدارة الائتمانية",
    downloadPdf: "تحميل PDF",
    english: 'الإنجليزية',
    arabic: 'العربية',
    choosePdfLanguageTitle: "اختر لغة التقرير",
    choosePdfLanguageDesc: "بأي لغة تود تحميل التقرير؟",
    cancel: "إلغاء",
    clearCsvTooltip: "مسح ملف CSV من الجلسة",
    csvClearedTitle: "تم مسح CSV",
    csvClearedDesc: "تمت إزالة بيانات CSV من الجلسة.",
    clearedCsvMessage: "لقد قمت بمسح بيانات CSV. كيف يمكنني مساعدتك الآن؟",
    translationErrorTitle: 'خطأ في الترجمة',
    translationErrorDesc: 'فشل إنشاء التقرير باللغة {{lang}}. يرجى المحاولة مرة أخرى.',
    generatingTranslatedPdf: 'جاري إنشاء ملف PDF مترجم...',
    trendsAndGraphsTitle: "الاتجاهات والتصورات",
    identifiedFlawsTitle: "العيوب والمخاطر المحددة",
    financialPerformanceTitle: "الأداء المالي",
    revenue: "الإيرادات",
    netIncome: "صافي الدخل",
    pdfGenerationError: "تعذر إنشاء تقرير PDF.",
    maintenanceMessage: "تخضع الخدمات للصيانة والتحديثات الرئيسية. الوقت المتبقي: {{time}}",
    
    // Abdullah Vision
    abdullahVisionTitle: "رؤية عبدالله",
    abdullahVisionDesc: "مساحة إبداعية لإنشاء الصور وتحسينها باستخدام الذكاء الاصطناعي.",
    textToImageTitle: "نص إلى صورة",
    textToImageDesc: "صف الصورة التي تريد إنشاءها.",
    imageEnhancementTitle: "تحسين الصور",
    imageEnhancementDesc: "قم بتحميل صورة لرفع جودتها.",
    videoEnhancementTitle: "تحسين الفيديو (قريباً)",
    videoEnhancementDesc: "قم بتحميل فيديو لتحسين دقته ووضوحه.",
    promptLabel: "الموجه",
    promptPlaceholder: "مثال: صورة واقعية لقطة ترتدي قبعة صغيرة، تجلس في مكتبة",
    generateButton: "إنشاء",
    generatingMessage: "عبدالله ينشئ صورتك...",
    uploadButton: "تحميل صورة",
    upscaleButton: "تحسين الصورة",
    upscalingMessage: "عبدالله يقوم بتحسين صورتك...",
    uploadVideo: "تحميل فيديو",
    resultTitle: "النتيجة",
    noResult: "ستظهر صورتك المنشأة أو المحسنة هنا.",
    imageGenFailedTitle: "فشل إنشاء الصورة",
    imageGenFailedDesc: "عذرًا، لم أتمكن من إنشاء صورة في هذا الوقت. يرجى المحاولة مرة أخرى لاحقًا.",
    imageUpscaleFailedTitle: "فشل تحسين الصورة",
    imageUpscaleFailedDesc: "عذرًا، لم أتمكن من تحسين الصورة. يرجى التأكد من أنها بتنسيق صالح والمحاولة مرة أخرى.",
    downloadButton: "تنزيل",
    startOver: "البدء من جديد",
    
    newSessionButton: "جلسة جديدة",
    newSessionTitle: "بدأت جلسة جديدة",
    newSessionDesc: "تم مسح محادثتك.",
    newSessionDescSpreadsheet: "تم مسح جدول البيانات والدردشة.",
    newSessionDescDA: "تم مسح لوحة معلومات تحليل البيانات الخاصة بك.",
    newSessionConfirmTitle: "هل أنت متأكد؟",
    newSessionConfirmDescChat: "سيؤدي هذا إلى مسح سجل الدردشة بالكامل وإزالة أي ملفات تم تحميلها. لا يمكن التراجع عن هذا الإجراء.",
    newSessionConfirmDescSpreadsheet: "سيؤدي هذا إلى مسح جدول البيانات بالكامل، بما في ذلك البيانات والمخططات، وإعادة تعيين الدردشة. لا يمكن التراجع عن هذا الإجراء.",
    newSessionConfirmButton: "بدء جلسة جديدة",

    // Abdullah Status
    abdullahStatusOnline: 'متصل',
    abdullahStatusOffline: 'غير متصل',

    // Nav
    chatTitle: 'الدردشة',
    aboutTitle: 'حول عبدالله',
    spreadsheetTitle: 'جدول البيانات',
    spreadsheetGuideTitle: 'دليل جدول البيانات',
    dataAnalyticsTitle: 'تحليل البيانات',
    knowledgeBaseTitle: 'قاعدة المعرفة',
    
    // Knowledge Base Page
    kbHeader: "قاعدة معرفة عبدالله",
    kbSubHeader: "أضف تعليماتك وقواعدك وبياناتك المخصصة التي سيتذكرها عبدالله في جميع المحادثات. هذا هو امتدادك الشخصي لدماغ عبدالله.",
    kbPlaceholder: "أدخل ملاحظاتك المخصصة هنا...\n\nعلى سبيل المثال:\n- لا تقترح أبدًا الاستثمار في العملات المشفرة.\n- عندما أطلب ملخصًا للسوق، قم دائمًا بتضمين مؤشر VIX.\n- تنتهي السنة المالية لشركتي في يونيو.",
    kbSaveButton: 'حفظ المعرفة',
    kbSavingButton: 'جاري الحفظ...',
    kbSaveSuccessTitle: 'تم حفظ قاعدة المعرفة',
    kbSaveSuccessDesc: "تم تحديث معرفة عبدالله.",
    kbSaveErrorTitle: 'فشل الحفظ',
    kbSaveErrorDesc: 'تعذر حفظ ملاحظاتك. يرجى المحاولة مرة أخرى.',
    kbLoadErrorTitle: 'فشل التحميل',
    kbLoadErrorDesc: 'تعذر تحميل ملاحظات قاعدة المعرفة الخاصة بك.',

    // Learn Page -> About Page
    learnPageTitle: 'حول عبدالله',
    learnIntro: 'عبدالله هو خبير استراتيجي مالي ومساعد مصرفي متقدم يعمل بالذكاء الاصطناعي، مصمم ليوفر لك تحليلات على مستوى المؤسسات وتنفيذ مهام وكيلية بكل سهولة. تفاعل بشكل طبيعي، واحصل على رؤى عميقة، وقم بأتمتة المهام المعقدة.',
    learnCapabilitiesTitle: "قدرات عبدالله الأساسية",
    capabilityHours: "التوفر:",
    chatAvailability: "24/7",
    spreadsheetAvailability: "24/7",
    daAvailability: "24/7",
    learnChatTitle: 'ذكاء مالي من الطراز المؤسسي',
    learnChatDesc: "تفاعل مع ذكاء اصطناعي يفهم دقائق الأمور المالية. قم بتحميل بيانات مالية معقدة، تقارير ائتمانية من مكاتب مثل 'ملاءة' في عُمان، أو بيانات قروض داخلية. عبدالله لا يقرأ فقط؛ بل يفهم، ويحلل، وينتقد. اطلب منه 'تحديد المخاطر الرئيسية في هذه الميزانية العمومية'، 'مقارنة نسبة السعر إلى الأرباح لهذه الشركة بمعايير الصناعة'، أو 'صياغة ملخص للجنة الائتمان'. يقدم عبدالله تحليلاً فوريًا بجودة مؤسسية باللغتين الإنجليزية والعربية، ليصبح شريكًا لا غنى عنه لمسؤولي الائتمان والمحللين وصناع القرار.",
    learnAbdullahVisionDesc: "أطلق العنان لإبداعك في مساحة مخصصة. بصفته مديرًا إبداعيًا من الطراز العالمي، يمكن لعبدالله إنشاء صور واقعية من الأوصاف النصية أو تحسين صورك الحالية إلى جودة مذهلة وعالية الدقة. رؤية عبدالله هو شريكك لإنشاء أصول بصرية مقنعة.",
    learnSpreadsheetTitle: 'جدول البيانات الوكيلي الحقيقي',
    learnSpreadsheetDesc: "هذا ليس مجرد جدول بيانات؛ إنها مساحة عمل ذكية حيث تأمر محللًا ماليًا خبيرًا بالذكاء الاصطناعي بلغة طبيعية. قل 'أنشئ نموذج DCF لمدة 5 سنوات لشركة SaaS'، 'أنشئ مخطط جانت لإطلاق منتج الربع الرابع'، أو 'حلل أرقام المبيعات هذه وقم بتمييز جميع المناطق التي كان أداؤها أقل بنسبة 15%'. يعمل عبدالله كوكيل ذكاء اصطناعي على أحدث طراز، حيث يفهم نيتك، وينظم البيانات، ويطبق الصيغ المعقدة، وينفذ عمليات متعددة الخطوات على الفور. مع مكتبة غنية من القوالب الاحترافية ومجموعة كاملة من أدوات التنسيق، فإنها تغير إنتاجيتك، وتنافس تطبيقات سطح المكتب التقليدية.",
    learnDATitle: 'لوحة معلومات ذكاء الأعمال المحادثة',
    learnDADesc: "حوّل البيانات الأولية إلى رؤى قابلة للتنفيذ باستخدام محرك ذكاء أعمال محادثة بالكامل. قم بتحميل ملفات CSV أو Excel أو PDF، وسيقوم عبدالله على الفور بإنشاء لوحة معلومات تفاعلية بالمقاييس والرسوم البيانية والجداول الرئيسية. واصل المحادثة لطلب تصورات جديدة أثناء التنقل. اطلب من عبدالله 'عرض إجمالي المبيعات حسب المنطقة في مخطط شريطي'، أو 'إنشاء مخطط دائري لشرائح العملاء'. يعمل عبدالله كمهندس بيانات ومطور ذكاء أعمال شخصي لك، محولة البيانات المعقدة إلى مرئيات واضحة وتفاعلية.",
    learnAITitle: 'مدعومة ببنية تحتية حديثة للذكاء الاصطناعي',
    learnAIDesc: "عبدالله مبني على بنية تحتية خاصة وحديثة للذكاء الاصطناعي. وهذا يمكنه من فهم المستندات المعقدة، والاستدلال على البيانات، واتباع التعليمات متعددة الخطوات، وإنشاء نصوص شبيهة بالإنسان، مما يجعله شريكًا ماليًا قويًا ومتعدد الاستخدامات.",
    learnSecurityTitle: 'أمان وخصوصية على مستوى المؤسسات',
    learnSecurityDesc: "تم تصميم عبدالله مع اعتبار الأمان مبدأً أساسيًا. تعمل ضمن بنية خاصة وحديثة، حيث يتم التعامل مع جميع عمليات معالجة البيانات والتفاعلات بأقصى درجات السرية. لا يتم استخدام بياناتك المالية، وبيانات الملكية، والمحادثات الحساسة أبدًا لتدريب النماذج الخارجية. مع التشفير من طرف إلى طرف وضوابط الوصول القوية، يوفر عبدالله بيئة آمنة ومتوافقة تلبي المعايير الصارمة للمؤسسات المالية، مما يضمن حماية معلوماتك الأكثر أهمية.",
    learnWhoBenefitsTitle: 'من يستفيد من عبدالله؟',
    learnRoleAnalystTitle: 'المحلل المالي',
    learnRoleAnalystDesc: 'سرّع أبحاثك، ونمذجة البيانات، وإعداد التقارير. دع عبدالله يتولى المهام المتكررة حتى تتمكن من التركيز على الرؤى الاستراتيجية.',
    learnRoleOfficerTitle: 'مسؤول الائتمان',
    learnRoleOfficerDesc: 'احصل على فهم أعمق وأسرع لمخاطر المتقدمين. حلل البيانات المالية وتقارير الائتمان في ثوانٍ لاتخاذ قرارات أكثر استنارة.',
    learnRoleExecutiveTitle: 'المدير التنفيذي',
    learnRoleExecutiveDesc: 'احصل على ملخصات عالية المستوى ومقاييس رئيسية عند الطلب. ابق على اطلاع وادفع بالاستراتيجية دون الغرق في التفاصيل.',
    gettingStartedTitle: "البدء: دليل سريع",
    gsChatStepTitle: "١. ابدأ محادثة",
    gsChatStepDesc: "انتقل إلى صفحة <strong>الدردشة</strong>. يمكنك البدء في التحدث إلى عبدالله على الفور. لتحليل أقوى، استخدم أزرار التحميل في شريط الرسائل لتوفير ملف PDF أو CSV كسياق لمحادثتك.",
    gsSpreadsheetStepTitle: "٢. تحكم في جدول بياناتك",
    gsSpreadsheetDesc: "اذهب إلى صفحة <strong>جدول البيانات</strong>. استخدم الشريط الجانبي للدردشة المدمج لإعطاء أوامر لعبدالله. يمكنك أيضًا استيراد ملفات Excel الخاصة بك باستخدام شريط الأدوات لجعل عبدالله يعمل مع بياناتك الخاصة.",
    gsDAStepTitle: "٣. حلل بياناتك",
    gsDAStepDesc: "توجه إلى صفحة <strong>تحليل البيانات</strong>. قم بتحميل مجموعة البيانات الخاصة بك (Excel، CSV ،PDF)، وسيقوم عبدالله على الفور ببناء لوحة معلومات. استخدم الدردشة لطلب المزيد من الأفكار والتصورات المحددة.",
    
    comingSoonAbdullahTitle: "مستقبل عبدالله: قدرات الذكاء الاصطناعي",
    comingSoonAbdullahDesc: "تطور عبدالله لا هوادة فيه. تركز خارطة طريقنا على بناء أقوى وكيل مالي استباقي يعمل بالذكاء الاصطناعي.",
    csAbdullahFeature1: "رؤى استباقية وكشف الحالات الشاذة",
    csAbdullahFeature2: "تكامل بيانات السوق في الوقت الحقيقي (الأسهم، العملات)",
    csAbdullahFeature3: "لوحات معلومات مخصصة للصحة المالية",
    csAbdullahFeature4: "تفاعل صوتي وكلامي متقدم",
    csAbdullahFeature5: "خزنة وإدارة آمنة للمستندات",
    csAbdullahFeature6: "إنشاء وجدولة التقارير تلقائيًا",
    csAbdullahFeature7: "تنبؤات استشرافية للتدفقات النقدية",
    csAbdullahFeature8: "تكامل مع التقويم والبريد الإلكتروني للتذكيرات المالية",
    csAbdullahFeature9: "تحليل ومقارنة بين عدة مستندات",
    csAbdullahFeature10: "تخطيط المدخرات والاستثمارات القائم على الأهداف",
    csAbdullahFeature11: "API آمن للتكامل المؤسسي",
    csAbdullahFeature12: "استعلام عن قواعد البيانات باللغة الطبيعية",
    csAbdullahFeature13: "مراقبة التغييرات في الامتثال والتنظيمات",
    csAbdullahFeature14: "تحليل مشاعر العملاء من المراسلات",
    csAbdullahFeature15: "أتمتة سير العمل الوكيلي المخصص",

    comingSoonSpreadsheetTitle: "مستقبل جداول البيانات: القوة الوكيلية",
    comingSoonSpreadsheetDesc: "يتحول جدول البيانات إلى مساحة عمل مستقلة تمامًا، مدعومة من عبدالله.",
    csSpreadsheetFeature1: "إنشاء الصيغ باللغة الطبيعية",
    csSpreadsheetFeature2: "إنشاء تلقائي للمخططات والرسوم البيانية من البيانات",
    csSpreadsheetFeature3: "قواعد التحقق من صحة البيانات مدعومة بالذكاء الاصطناعي",
    csSpreadsheetFeature4: "إنشاء فوري للجداول المحورية عبر الدردشة",
    csSpreadsheetFeature5: "تنظيف البيانات وإزالة التكرارات تلقائيًا",
    csSpreadsheetFeature6: "تنسيق شرطي ذكي",
    csSpreadsheetFeature7: "بيانات الأسهم والبيانات المالية في الوقت الحقيقي بالخلايا",
    csSpreadsheetFeature8: "استيراد تلقائي للبيانات من مصادر الويب",
    csSpreadsheetFeature9: "تحرير تعاوني مباشر بمساعدة الذكاء الاصطناعي",
    csSpreadsheetFeature10: "سجل إصدارات كامل مع ملخصات بالذكاء الاصطناعي",
    csSpreadsheetFeature11: "تحليل سيناريوهات متقدم و Goal Seek",
    csSpreadsheetFeature12: "إنشاء تقارير تلقائية من القوالب",
    csSpreadsheetFeature13: "التكامل مع مصادر بيانات خارجية (APIs)",
    csSpreadsheetFeature14: "كتابة نصوص بايثون داخل الخلايا للتحليل المتقدم",
    csSpreadsheetFeature15: "تدقيق البيانات وتتبع الأخطاء بالذكاء الاصطناعي",
    
    comingSoonDATitle: "مستقبل التحليلات: محرك ذكاء أعمال وكيلي",
    comingSoonDADesc: "نحن نعمل على تطوير عبدالله ليصبح منصة ذكاء أعمال أصلية للذكاء الاصطناعي تنافس الأدوات التقليدية.",
    csDAFeature1: "إنشاء لوحة معلومات تفاعلية من الدردشة",
    csDAFeature2: "أدوات تحويل بيانات مرئية شبيهة بـ Power Query",
    csDAFeature3: "تحويل اللغة الطبيعية إلى تعبيرات شبيهة بـ DAX",
    csDAFeature4: "بناء تقارير وقصص بيانات تلقائية",
    csDAFeature5: "كشف الحالات الشاذة والتنبيهات في الوقت الحقيقي",
    csDAFeature6: "نماذج التحليلات التنبؤية والتنبؤ",
    csDAFeature7: "دمج ومزج البيانات من مصادر متعددة",
    csDAFeature8: "تحليل السبب الجذري المدعوم بالذكاء الاصطناعي",
    csDAFeature9: "مرئيات مخصصة وقابلية توسيع API",
    csDAFeature10: "إنشاء خطوط أنابيب ETL تلقائية",

    getStartedAbdullah: 'ابدأ مع عبدالله',
    getStartedSpreadsheet: 'أو, ابدأ مع جدول البيانات',

    // Spreadsheet Page
    chatWithAbdullah: "الدردشة مع عبدالله",
    closeChat: "إغلاق الدردشة",
    abdullahSpreadsheetHello: "مرحباً! أنا مساعد جداول بيانات وكيلي كامل الميزات. يمكنني مساعدتك في إدخال البيانات، والنمذجة المالية، والمخططات، والمزيد. كيف يمكنني مساعدتك؟",
    spreadsheetPlaceholder: "مثال: أنشئ قالب فاتورة",
    send: "إرسال",
    showChat: "إظهار الدردشة",
    hideChat: "إخفاء الدردشة",
    importSuccessTitle: "تم الاستيراد بنجاح",
    importSuccessDesc: "تم استيراد \"{{fileName}}\" بنجاح.",
    importFailedTitle: "فشل الاستيراد",
    importFailedDesc: "حدث خطأ أثناء معالجة ملف Excel الخاص بك.",
    abdullahSpreadsheetFileLoaded: "لقد قمت بتحميل \"{{fileName}}\" في جدول البيانات. كيف يمكنني مساعدتك به؟",
    abdullahSpreadsheetError: "عذراً، واجهتني مشكلة. يرجى المحاولة مرة أخرى.",
    toolbarFile: "ملف",
    toolbarTemplates: "قوالب",
    templateInvoice: "فاتورة",
    templatePayroll: "كشف رواتب",
    templateExpense: "سداد المصروفات",
    templateBalanceSheet: "الميزانية العمومية",
    templateIncomeStatement: "بيان الدخل",
    templateCashFlow: "بيان التدفقات النقدية",
    templateBudget: "الميزانية الشهرية",
    templateGantt: "مخطط جانت للمشروع",
    templateGeneralLedger: "دفتر الأستاذ العام",
    templateSalesLedger: "دفتر أستاذ المبيعات",
    templatePurchaseLedger: "دفتر أستاذ المشتريات",
    templateFinancialModel: 'نموذج مالي ثلاثي القوائم',
    templateDCF: 'تقييم التدفقات النقدية المخصومة',
    templateAppliedTitle: "تم تطبيق القالب",
    templateAppliedDesc: "تم تحميل القالب في الجدول.",
    toolbarHome: "الرئيسية",
    toolbarInsert: "إدراج (قريباً)",
    toolbarFormulas: "صيغ (قريباً)",
    toolbarData: "بيانات (قريباً)",
    toolbarReview: "مراجعة (قريباً)",
    toolbarView: "عرض (قريباً)",
    toolbarFullscreen: "ملء الشاشة",
    toolbarExitFullscreen: "الخروج من ملء الشاشة",
    toolbarDownload: "تنزيل",
    toolbarImport: "استيراد",
    tooltipPaste: "لصق (استخدم Ctrl/Cmd+V)",
    tooltipCut: "قص",
    tooltipCopy: "نسخ",
    tooltipFormatPainter: "نسخ التنسيق (قريباً)",
    tooltipBold: "عريض",
    tooltipItalic: "مائل",
    tooltipUnderline: "تسطير",
    tooltipFontColor: "لون الخط",
    tooltipFillColor: "لون التعبئة",
    tooltipAlignLeft: "محاذاة لليسار",
    tooltipCenter: "توسيط",
    tooltipAlignRight: "محاذاة لليمين",
    tooltipWrapText: "التفاف النص",
    tooltipMergeCenter: "دمج وتوسيط",
    tooltipAutoSum: "جمع تلقائي (قريباً)",
    tooltipSortFilter: "فرز وتصفية (قريباً)",
    tooltipFindSelect: "بحث وتحديد (قريباً)",
    chartsTitle: "المخططات",

    // Spreadsheet Guide Page
    sgTitle: "دليل جدول البيانات",
    sgHeader: "جدول البيانات الوكيلي",
    sgSubHeader: "هذه ليست مجرد شبكة من الخلايا. إنها مساحة عمل ذكية حيث تأمر الذكاء الاصطناعي بأداء مهام معقدة. سيوضح لك هذا الدليل كيفية القيام بذلك.",
    sgCoreCapabilitiesTitle: "القدرات الأساسية",
    sgFeatureAIAssistantTitle: "مساعد الذكاء الاصطناعي",
    sgFeatureAIAssistantDesc: "استخدم اللغة الطبيعية في لوحة الدردشة لأمر عبدالله بأداء أي مهمة، من إدخال البيانات إلى النمذجة المالية المعقدة.",
    sgFeatureTemplatesTitle: "قوالب قوية",
    sgFeatureTemplatesDesc: "ابدأ عملك بمكتبة من القوالب الاحترافية والمعدة مسبقًا للمحاسبة والتمويل وإدارة المشاريع.",
    sgFeatureFormulasTitle: "صيغ كاملة الميزات",
    sgFeatureFormulasDesc: "استفد من مكتبة ضخمة من مئات الوظائف، تمامًا كما في تطبيقات جداول البيانات التقليدية. يمكن لعبدالله بناء صيغ لك.",
    sgFeatureDataToolsTitle: "أدوات بيانات متقدمة",
    sgFeatureDataToolsDesc: "اطلب من عبدالله فرز البيانات، تصفيتها، العثور على التكرارات، أو حتى إنشاء ملخصات شبيهة بالجداول المحورية على الفور.",
    sgGettingStartedTitle: "كيف يعمل: سير عملك في 3 خطوات",
    sgGettingStartedDesc: "العمل مع جدول البيانات الوكيلي هو عملية محادثة بسيطة.",
    sgStep1Title: "ابدأ بالبيانات",
    sgStep1Desc: "يمكنك البدء بصفحة فارغة، أو استيراد ملف Excel/CSV موجود، أو تحديد قالب مُعد مسبقًا من قائمة 'القوالب'.",
    sgStep2Title: "أصدر أمرًا لعبدالله",
    sgStep2Desc: "استخدم لوحة الدردشة على اليمين لإخبار عبدالله بما تريد القيام به باللغة الإنجليزية أو العربية البسيطة.",
    sgStep2Example: "احسب صافي الربح للربع الثالث وقم بتمييزه باللون الأخضر.",
    sgStep3Title: "راجع النتيجة",
    sgStep3Desc: "سيقوم عبدالله بتفسير أمرك، وإجراء العمليات اللازمة (مثل إدراج الصيغ وتطبيق التنسيق)، وتأكيد الإجراء. يتم تحديث الجدول على الفور.",
    sgStep3Example: "تم. لقد حسبت صافي الربح في الخلية E14 وطبقت التنسيق.",
    sgAbdullahCommandsTitle: "أوامر مثال لعبدالله",
    sgCmdDataEntryTitle: "إدخال البيانات ومسك الدفاتر",
    sgCmdDataEntryDesc: "يمكن أن يعمل عبدالله كمحاسب آلي لك.",
    sgCmdDataEntryExample: "سجل عملية بيع 500 وحدة بسعر 12.50 ريال لكل منها إلى 'شركة المثال' بتاريخ اليوم.",
    sgCmdFinancialAnalysisTitle: "التحليل المالي والنمذجة",
    sgCmdFinancialAnalysisDesc: "اطلب من عبدالله إجراء حسابات مالية معقدة.",
    sgCmdFinancialAnalysisExample: "ما هي صافي القيمة الحالية للتدفقات النقدية في C5:C10 بمعدل خصم 8%؟",
    sgCmdFormattingTitle: "التنسيق والتدقيق",
    sgCmdFormattingDesc: "أتمتة التنظيم البصري والتحقق من صحة البيانات.",
    sgCmdFormattingExample: "ابحث عن جميع الصفوف حيث يكون العمود D أكبر من العمود C واجعل خلفيتها حمراء فاتحة.",
    sgCmdChartsTitle: "المخططات والتصور",
    sgCmdChartsDesc: "حوّل بياناتك إلى رؤى.",
    sgCmdChartsExample: "أنشئ مخططًا شريطيًا يوضح إجمالي المبيعات حسب المنطقة من العمودين A و F.",
    sgFunctionLibraryTitle: "مكتبة الوظائف والصيغ",
    sgFunctionLibraryDesc: "عبدالله بارع في مكتبة واسعة من الوظائف ويمكنه إنشاء صيغ عند الطلب. إليك بعض الوظائف الرئيسية المتاحة:",
    sgFuncMathLogicTitle: "الرياضيات والمنطق",
    sgFuncLookupTitle: "البحث والمراجع",
    sgFuncFinancialTitle: "المالية",
    sgFuncTextTitle: "النص",
    sgFuncDateTimeTitle: "التاريخ والوقت",
    sgFuncStatisticalTitle: "الإحصاء والتنبؤ",

    // Data Analytics Page
    daUploadPromptTitle: "لوحة معلومات مدعومة بالذكاء الاصطناعي",
    daUploadPromptDesc: "قم بتحميل ملف البيانات الخاص بك (XLSX، CSV، أو PDF) ليقوم عبدالله بتحليله وإنشاء لوحة معلومات تفاعلية.",
    daUploadButton: "تحميل ملف البيانات",
    daGeneratingDashboardTitle: "جاري إنشاء لوحة معلومات الذكاء الاصطناعي...",
    daGeneratingDashboardDesc: "يرجى الانتظار بينما يقوم عبدالله بتحليل بياناتك وبناء لوحة معلوماتك.",
    analysisResultTitle: "نتيجة التحليل",
    daSummaryTitle: "ملخص الذكاء الاصطناعي",
    daUnsupportedFileType: 'نوع ملف غير مدعوم. يرجى تحميل ملف CSV أو XLSX أو PDF.',
    daAnalysisFailedDesc: 'فشل التحليل. قد يكون الملف تالفًا أو بتنسيق غير مدعوم أو أن نموذج الذكاء الاصطناعي غير متاح حاليًا.',
    daKeyInsightsTitle: 'رؤى رئيسية',
    daDownloadPdfButton: 'تحميل PDF',
    daGeneratingPdfTitle: 'جاري إنشاء تقرير PDF...',
    daPdfGenerationFailedTitle: 'فشل إنشاء PDF',
    daPdfGenerationFailedDesc: 'حدث خطأ أثناء محاولة إنشاء تقرير PDF.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key: string, replacements?: { [key: string]: string | number }) => {
    let translation = translations[language][key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            translation = translation.replace(`{{${rKey}}}`, String(replacements[rKey]));
        });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
